name: Update NASDAQ-100 Constituents
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@main
      - name: Install and setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip3 install -r scripts/requirements.txt
      - name: Update data
        run: |
          python3 scripts/nasdaq100_companies.py
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update NASDAQ-100 constituents
